menu:
# - {name: 'People', url: '/people'}
- {name: 'CV', url: '/cv'}
- {name: 'Publications', url: '/publications'}
- {name: 'Projects', url: '/projects'}
- {name: 'Contact', url: '/contact'}
- {name: 'Courses', url: '/courses'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

projects:
- {name: 'Vector Calculus Project', url: 'vector-calculus'}
- {name: 'Quantum Mechanics Project', url: 'quantum-mechanics'}
- {name: 'Stellar Structures Project', url: 'stellar-structures'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jose-alfredo-rosas-cordova'}
- {icon: 'github', link: 'https://github.com/JARC99'}


contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
