menu:
- {name: 'Homse', url: ''}
- {name: 'Publications', url: '/publications'}
- {name: 'Projects', url: '/projects'}
- {name: 'Contact', url: '/contact'}

projects:
- {name: 'Vector Calculus Project', url: 'vector-calculus'}
- {name: 'Quantum Mechanics Project', url: 'quantum-mechanics'}
- {name: 'Stellar Structures Project', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/JARC99'}
- {icon: 'fab fa-linkedin', link: 'https://www.linkedin.com/in/jose-alfredo-rosas-cordova'}
- {icon: 'fas fa-binoculars', link: 'https://www.inaturalist.org/people/jarc'}
- {icon: 'fab fa-youtube', link: 'https://www.youtube.com/@JARC99_'}

contacts:
- {name: 'José Alfredo Rosas Córdova', title: 'M. Sc. Mechanical Engineering Student', department: 'Fakultät Maschinenbau', institution: 'Leibniz Universität Hannover', institution_address: 'An der Universität 1, 30823  Garbsen', email: 'jarosascordova@gmail.com', image: 'assets/img/contact.jpg'}
